### ISSUE TITLE
Dark theme ~~Suggestion to remove GA~~

### ISSUE THREAD

**Issue by leaty** [GeorgeV220/champ-r#1]
As the title says. Unfortunately I also made a really quick and dirty dark theme for my eyes at the same time and didn't bother with branches. But it's a tiny change, see here https://github.com/leaty/champ-r/commit/a6fb372e245863cc839cef522a6745a3b1b2deeb

I'll make a PR if you agree.

**Comment by GeorgeV220** [comment]
Hello, 
Thank you for the suggestion. If you want open a pull request. Now about the dark theme, if you made it work with a button it would be awesome

**Comment by leaty** [comment]
PR coming right up.

For the dark theme, it's definitely a no currently. It was quick and dirty after all, it's also a bit of a mess where all the theming options are in champ-r. Maybe some other time I could try, or just yoink it from here https://github.com/leaty/champ-r/commit/7b6b265feed6898e5e23f843e62b1b1466233080 :slightly_smiling_face:

**Comment by leaty** [comment]
Here's a [darker theme](https://github.com/leaty/champ-r/releases/tag/v1.1.13-league-no-ga) supposed to mimic the client better, but as you can see it's far from perfect. I don't know where to customize the buttons except switching between the defaults "Dark" and "Light" provided by `base-ui`.

![screen 2021-11-22 18 42 43](https://user-images.githubusercontent.com/4429327/142910737-e0387863-9a99-4105-be72-eed94b135a10.png)

**Comment by GeorgeV220** [comment]
I will probably implement it with a switch for light and dark theme. Thank you for your contribution to this project!!
