### ISSUE TITLE
The app broke

### ISSUE THREAD

**Issue by PaulDotSH** [GeorgeV220/champ-r#5]
The app broke, the import button is disabled and when the pop up appears it's stuck on loading

**Comment by PaulDotSH** [comment]
It was randomly fixed by restarting my pc for some reason

**Comment by PaulDotSH** [comment]
It randomly comes back, so it should be investigated

**Comment by GeorgeV220** [comment]
I'm currently working to merge the upstream, when I finish and have a working instance on linux, I will look into it.

**Comment by GeorgeV220** [comment]
Hello, please try the latest version

**Comment by PaulDotSH** [comment]
> Hello, please try the latest version

The Import button is disabled, I can't seem to fix it

**Comment by GeorgeV220** [comment]
> > Hello, please try the latest version
> 
> The Import button is disabled, I can't seem to fix it

Add me on Discord so we can check it together: GeorgeV22#3200
